<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Node Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{

}
